tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

# brew "asdf"
# brew "awscli"
brew "curl"
# brew "ffmpeg"
brew "fzf"
# brew "gifsicle"
brew "git"
# brew "git-lfs"
brew "jq"
brew "rcm"
brew "tmux"
brew "tree"
brew "wget"
# brew "youtube-dl"
brew 'zplug'

# cask "alacritty"
# cask "kitty"